config/routes.rb
Rails.application.routes.draw do
 

  root 'transactions#index'
  resources :accounts
  resources :accounts, as: 'mains'
  resources :accounts, as: 'branches'
  resources :people
  resources :people, as: 'natural_people'
  resources :people, as: 'legal_people'
  resources :transactions, except: [:destroy, :edit, :update]

  post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'transaction_reversal'

  # API
  scope '/api', defaults: { format: :json } do
    resources :transactions, except: [:destroy, :edit, :update]
    resources :people
    resources :accounts

    post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'api_transaction_reversal'
  end

end

app/models/person.rb
class Person < ApplicationRecord
  enum status: [:active, :inactive]

  scope :actives, -> { where(status: 0) }

  has_many :accounts

  validates :type, presence: true

  def name
    self.full_name.blank? ? self.company_name : self.full_name
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.actives.order('id DESC').map do |person|
      if person.type == 'NaturalPerson'
        {id:person.id, name: person.full_name, document: CPF.new(person.cpf).formatted, type: 'Pessoa física'}
      else
        {id:person.id, name: person.company_name, document: person.cnpj, type: 'Pessoa jurídica'}
      end
    end
    respond_to do |format|
      format.html
      format.json { render json: @people}
    end
  end

  def new
    @person = Person.new
  end

  def show
    if @person
      respond_to do |format|
        format.html
        format.json { render json: @person}
      end
    else
      respond_to do |format|
        format.html { redirect_to people_path, notice: "Usuário não existe" }
        format.json { head :not_found }
      end
    end
  end
  def edit; end

  def create
    @person = Person.new(people_params)
    if @person.save
      respond_to do |format|
        format.html { redirect_to people_path, notice: "Cadastro realizado com sucesso" }
        format.json { render json: @person, status: :created}
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: {errors: @person.errors }, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @person.update(people_params)
      respond_to do |format|
        format.html { redirect_to people_path, notice: "Informações atualizadas com sucesso" }
        format.json { render json: @person}
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: {errors: @person.errors } }
      end
    end
  end

  def destroy
    @person.accounts.update_all({status: 'inactive'})
    @person.update({status: 'inactive'})
    respond_to do |format|
      format.html { redirect_to people_path, notice: "Usuário excluido com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    def set_person
      @person = Person.find_by(id: params[:id])
    end

    def people_params
      params[:person] = params[:natural_person] if params[:natural_person]
      params[:person] = params[:legal_person] if params[:legal_person]
      params[:person][:type] = params[:type] if params[:type] 

      params.require(:person).permit(:full_name,:cpf,:birthdate,:company_name,:trade_name,:cnpj,:type)

    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/edit.html.erb
<div class="col-md-6">
  <% if @person.type == 'NaturalPerson' %>
    <h1 class="page-header">Pessoa Física</h1>
    <%= render partial: "people/shared/form_natural", locals: {readonly: false}%>
  <% end %>
  
  <% if @person.type == 'LegalPerson' %>
    <h1 class="page-header">Pessoa Jurídica</h1>
    <%= render partial: "people/shared/form_legal", locals: {readonly: false} %>
  <% end %>
</div>

app/views/people/index.html.erb
<h1 class="page-header">Usuários</h1>
<div class="panel panel-default">
  <div class="panel-heading">
      Todas Usuários
      <%= link_to new_person_path, class: "btn btn-success btn-circle pull-right", style: "margin-top:-5px;" do %>
        <i class="fa fa-plus"></i>
      <% end %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover" id="people_list_table">
        <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Documento</th>
              <th>Tipo</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            <% @people.each do |person| %>
              <tr class="<%= person[:type] %>">
                <td><%= person[:id] %></td>
                <td><%= person[:name] %></td>
                <td><%= person[:document] %></td>
                <td><%= person[:type] %></td>
                <td style="width: 100px;">
                  <%= link_to person_path(person[:id]), class: "btn btn-primary btn-circle" do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to edit_person_path(person[:id]), class: "btn btn-warning btn-circle" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to person_path(person[:id]), method: :delete,data: {confirm: 'Deseja realmente desativar este usuario ?'} , class: "btn btn-danger btn-circle" do %>
                    <i class="fa fa-close"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<h1 class="page-header">Cadastro de Usuário</h1>
<div class="col-md-6">
  <ul  class="nav nav-pills">
    <li class="<%= @person.type == 'NaturalPerson' || @person.type.nil?  ? 'active' : ''  %>">
      <a href="#1b" data-toggle="tab">Nova Pessoa Física</a>
    </li>
    <li class="<%= @person.type == 'LegalPerson' ? 'active' : ''  %>">
      <a href="#2b" data-toggle="tab">Nova Pessoa Juridica</a>
    </li>
  </ul>

  <div class="tab-content clearfix">
    <div class="tab-pane <%= @person.type == 'NaturalPerson' || @person.type.nil?  ? 'active' : ''  %>" id="1b">
      <h3>Pessoa Física</h3>
      <%= render partial: "people/shared/form_natural", locals: {readonly: false}%>
    </div>
    <div class="tab-pane <%= @person.type == 'LegalPerson' ? 'active' : ''  %>" id="2b">
      <h3>Pessoa Jurídica</h3>
      <%= render partial: "people/shared/form_legal", locals: {readonly: false}%>
    </div>
  </div>
</div>



<%# render partial: "people/shared/form", 
           :locals => {title_action: 'Cadastrando usuário', action: 'create', readonly: false}  %>

app/views/people/show.html.erb
<div class="col-md-6">
  <% if @person.type == 'NaturalPerson' %>
    <h1 class="page-header">Pessoa Física</h1>
    <%= render partial: "people/shared/form_natural", locals: {readonly: true}%>
  <% end %>
  
  <% if @person.type == 'LegalPerson' %>
    <h1 class="page-header">Pessoa Jurídica</h1>
    <%= render partial: "people/shared/form_legal", locals: {readonly: true} %>
  <% end %>
</div>