config/routes.rb
Rails.application.routes.draw do
 

  root 'transactions#index'
  resources :accounts
  resources :accounts, as: 'mains'
  resources :accounts, as: 'branches'
  resources :people
  resources :people, as: 'natural_people'
  resources :people, as: 'legal_people'
  resources :transactions, except: [:destroy, :edit, :update]

  post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'transaction_reversal'

  # API
  scope '/api', defaults: { format: :json } do
    resources :transactions, except: [:destroy, :edit, :update]
    resources :people
    resources :accounts

    post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'api_transaction_reversal'
  end

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  def index
    @transactions = Transaction.all
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show]
  
  def index
    @transactions = Transaction.order('id DESC')
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @transactions}
    end
  end

  def new
    @transaction = Transaction.new
  end

  def show; end

  def create  
    @transaction = Transaction.new(transaction_params)
    if @transaction.save()
      respond_to do |format|
        format.html { redirect_to transactions_path, notice: "Transação realizada com sucesso"; }
        format.json { render json: @transaction }
      end
    else
       respond_to do |format|
        format.html { render :new }
        format.json { render json: { errors: @transaction.errors} }
      end
    end
  end

  def reversal
    token = params[:transaction_token].blank? ? nil : params[:transaction_token]
    transaction = Transaction.find_by(id: params[:id], token: token)   
                               
    if transaction && transaction.reversal?
      respond_to do |format|
        format.html { redirect_to transactions_path, alert: "Não é possivel cancelar um estorno." }
        format.json { render json: { errors: 'Não é possivel cancelar um estorno.'} }
      end
    elsif transaction && transaction.canceled?
      respond_to do |format|
        format.html { redirect_to transactions_path, alert: "Transação já estornada" }
        format.json { render json: { errors: 'Transação já estornada'} }
      end  
    elsif transaction && !transaction.reversal? && !transaction.canceled?  
      transaction_reversal = Transaction.create(origin: transaction.destination,
                                                destination: transaction.origin,
                                                amount: transaction.amount,
                                                transaction_type: 'reversal');
      transaction.status = 'canceled'
      transaction.save()
      respond_to do |format|
        format.html { redirect_to transactions_path, notice: "Estorno realizado com sucesso" }
        format.json { render json: transaction_reversal }
      end
    elsif !transaction
      respond_to do |format|
        format.html { redirect_to transactions_path, alert: "Código de Autorização inválido. Entre em contato"; }
        format.json { render json: { errors: 'Código de Autorização inválido. Entre em contato'} }
      end
    end
  end

  private
    def transaction_params
      params.require(:transaction).permit(:origin_id,:destination_id,:amount,:transaction_type)      
    end

    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<h1 class="page-header">Transações</h1>
<div class="panel panel-default">
  <div class="panel-heading">
      Todas as transações
      <%= link_to new_transaction_path, class: "btn btn-success btn-circle pull-right", style: "margin-top:-5px;" do %>
        <i class="fa fa-plus"></i>
      <% end %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover" id="transaction_list_table">
        <thead>
            <tr>
              <th>#</th>
              <th>Origem</th>
              <th>Operação</th>
              <th>Valor</th>
              <th>Destino</th>
              <th>Situação</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            <% @transactions.each do |transaction| %>
              <tr class="<%= transaction.status %>">
                <td><%= transaction.id %></td>
                <td><%= transaction.origin.name %></td>
                <td><%= t("activerecord.attributes.transaction.type.#{transaction.transaction_type}") %></td>
                <td><%= transaction.amount %></td>
                <td><%= transaction.destination.name %></td>
                <td><%= t("activerecord.attributes.transaction.situation.#{transaction.status}") %></td>
                <td style="width: 100px;">
                  <%= link_to transaction_path(transaction), class: "btn btn-primary btn-circle" do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<%= render partial: "transactions/shared/form", 
           :locals => {title_action: 'Criando uma transação', action: 'create', readonly: false}  %>

app/views/transactions/show.html.erb
<%= render partial: "transactions/shared/form", 
          :locals => {title_action: 'Visualização', action: 'reversal', readonly: true}  %>