config/routes.rb
Rails.application.routes.draw do
 

  root 'transactions#index'
  resources :accounts
  resources :accounts, as: 'mains'
  resources :accounts, as: 'branches'
  resources :people
  resources :people, as: 'natural_people'
  resources :people, as: 'legal_people'
  resources :transactions, except: [:destroy, :edit, :update]

  post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'transaction_reversal'

  # API
  scope '/api', defaults: { format: :json } do
    resources :transactions, except: [:destroy, :edit, :update]
    resources :people
    resources :accounts

    post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'api_transaction_reversal'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Account Manager</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
</head>
<body>
  <div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Account Manager V1.0</a>
        </div>
        <div class="navbar-default sidebar" role="navigation">
          <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
              <li>
                <%= link_to transactions_path do %>
                <i class="fa fa-line-chart" aria-hidden="true"></i> Transações
                <% end %>
              </li>
              <li>
                <%= link_to people_path do %>
                  <i class="fa fa-address-book" aria-hidden="true"></i> Pessoas
                <% end %>
              </li>
              <li>
                <%= link_to accounts_path do %>
                  <i class="fa fa-usd" aria-hidden="true"></i> Contas
                <% end %>
              </li>
            </ul>
          </div>
          <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">    
              <%= yield %>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
  </div>
    <% if notice %>
        <script>
            $.notify("<%= notice %>","success");
        </script>
    <% end %>

    <% if alert %>
        <script>
            $.notify("<%= alert %>","error");
        </script>
    <% end %>
</body>

</html>