config/routes.rb
Rails.application.routes.draw do
 

  root 'transactions#index'
  resources :accounts
  resources :accounts, as: 'mains'
  resources :accounts, as: 'branches'
  resources :people
  resources :people, as: 'natural_people'
  resources :people, as: 'legal_people'
  resources :transactions, except: [:destroy, :edit, :update]

  post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'transaction_reversal'

  # API
  scope '/api', defaults: { format: :json } do
    resources :transactions, except: [:destroy, :edit, :update]
    resources :people
    resources :accounts

    post '/transactions/:id/reversal', to: 'transactions#reversal', as: 'api_transaction_reversal'
  end

end

app/models/account.rb
class Account < ApplicationRecord
  enum status: [:active, :inactive]
  belongs_to :person
  belongs_to :parent, foreign_key: "parent_id", class_name: "Account", optional: true
  has_many :branches, foreign_key: "parent_id", class_name: "Account", dependent: :delete_all

  scope :actives, -> { where(status: 0) }

  validates :type, presence: true

  def main?
    self.type.downcase == 'main'
  end

  def branch?
    self.type.downcase == 'branch'
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  
  def index
    @accounts = Account.actives.order('id DESC')
    respond_to do |format|
      format.html
      format.json{ render json: @accounts }
    end
  end

  def new
    @account = Account.new
  end

  def show
    @transactions_input = Transaction.where("destination_id = :account",{account: @account.id })
    @transactions_output = Transaction.where("origin_id = :account",{account: @account.id })
    respond_to do |format|
      format.html
      format.json { render json: {account: @account, transactions_input:@transactions_input, transactions_output:@transactions_output} }
    end
  end

  def destroy
    @account.update({status: 'inactive'})
    respond_to do |format|
      format.html{ redirect_to accounts_path, notice: 'Conta desativada com sucesso' }
      format.json { head :no_content }
    end    
  end

  def edit; end

  def update
    if @account.update(account_params)
      respond_to do |format|
        format.html { redirect_to account_path(@account) }
        format.json { render json: @account }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: {errors: @account.errors} }
      end
    end
  end
  
  def create
    @account = Account.new(account_params)
    if @account.save
      respond_to do |format|
        format.html { redirect_to accounts_path, notice: 'Conta criada com sucesso' }
        format.json { render json: @account, status: :created}
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: {errors: @account.errors }, status: :unprocessable_entity }
      end
    end
  end

  private
    def account_params
      params[:account] = params[:main] if params[:main]
      params[:account] = params[:branch] if params[:branch]
      params.require(:account).permit(:name, :type, :person_id, :parent_id)
    end

    def set_account
      @account = Account.find(params[:id])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<div class="col-md-6">
  <h1 class="page-header">Conta</h1>
  <%= render partial: 'accounts/shared/form', locals: {readonly: false} %>
</div>

app/views/accounts/index.html.erb
<h1 class="page-header">Contas</h1>
<div class="panel panel-default">
  <div class="panel-heading">
      Todas as contas
      <%= link_to new_account_path, class: "btn btn-success btn-circle pull-right", style: "margin-top:-5px;" do %>
        <i class="fa fa-plus"></i>
      <% end %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover" id="people_list_table">
        <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Responsável </th>
              <th>Tipo</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            <% @accounts.each do |account| %>
              <tr class="<%= account.type %>">
                <td><%= account.id %></td>
                <td><%= account.name %></td>
                <td>
                <%= link_to account.person.name, person_path(account.person) %>
                </td>
                <td><%= account.type %></td>
                <td style="width: 100px;">
                  <%= link_to account_path(account), class: "btn btn-primary btn-circle" do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to edit_account_path(account), class: "btn btn-warning btn-circle" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to account_path(account), method: :delete,data: {confirm: 'Deseja realmente desativar ?'} , class: "btn btn-danger btn-circle" do %>
                    <i class="fa fa-close"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="col-md-6">
  <h1 class="page-header">Contas</h1>
  <%= render partial: 'accounts/shared/form', locals: {readonly: false} %>
</div>

app/views/accounts/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1 class="page-header">Conta</h1>
    <%= render partial: 'accounts/shared/form', locals: {readonly: true} %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
  <!-- /.panel-heading -->
    <div class="panel-body">
    <h2>Todas as entradas</h2>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
              <tr>
                <th>Operação</th>
                <th>Origem</th>
                <th>Valor</th>
                <th>Situação</th>
                <th></th>
              </tr>
          </thead>
          <tbody>
              <% @transactions_input.each do |transaction| %>
                <tr class="<%= transaction.status %>">
                  <td><%= t("activerecord.attributes.transaction.type.#{transaction.transaction_type}") %></td>
                  <td><%= transaction.origin.name %></td>
                  <td><%= transaction.amount %></td>
                  <td><%= t("activerecord.attributes.transaction.situation.#{transaction.status}") %></td>
                  <td>
                    <%= link_to transaction_path(transaction), class: "btn btn-primary btn-circle" do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col-md-6">
  <!-- /.panel-heading -->
    <div class="panel-body">
      <h2>Todas as saídas</h2>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
              <tr>
                <th>Destino</th>
                <th>Operação</th>
                <th>Valor</th>
                <th>Situação</th>
                <th></th>
              </tr>
          </thead>
          <tbody>
              <% @transactions_output.each do |transaction| %>
                <tr class="<%= transaction.status %>">
                  <td><%= transaction.destination.name %></td>
                  <td><%= t("activerecord.attributes.transaction.type.#{transaction.transaction_type}") %></td>
                  <td><%= transaction.amount %></td>
                  <td><%= t("activerecord.attributes.transaction.situation.#{transaction.status}") %></td>
                  <td>
                    <%= link_to transaction_path(transaction), class: "btn btn-primary btn-circle" do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>  